### ISSUE TITLE
나에게 맞는 향수 찾기 소개 화면 제작

### ISSUE THREAD

**Issue by wjdxor133** [perfumer24/perfumer-product#9]
## 어떤 문제로 인해 이 기능을 원하게 되셨나요?

사용자가 어떤 향수를 선호하는지 찾아볼수 있게 흥미를 유발하려고

## 원하시는 해결 방안을 알려주세요.

나와 맞는 향수를 찾을 수 있다는 메시지를 전달하는 화면을 제작

## 다른 대안은 고려해 보셨나요?

- 없음

## 추가 정보를 남겨주세요.

아래 화면 참고

https://github.com/perfumer24/perfumer-product/assets/47416686/a77b36eb-88d3-418b-beff-d3716f3baa02

**Comment by mattt0204** [comment]
예시를 드신거죠? 비교해서 찾을 수 있다는 문구로 가면 될 것 같음

**Comment by wjdxor133** [comment]
@mattt0204 
네네, 저 예시 기반으로 작업했습니다~
